name: Bug Report
description: Report a problem
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting this issue! Please provide as much detail as possible.
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what went wrong...
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected outcome...
    validations:
      required: false
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what you observed...
    validations:
      required: false
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Frontend
        - Backend
        - AI/RAG System
        - Database
        - File Processing
        - Timetable
        - Notes
        - Todo List
        - Pen2PDF
        - Other
    validations:
      required: false
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Tell us about your environment
      placeholder: |
        - OS: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
        - Browser: [e.g., Chrome 120, Firefox 121]
        - Node.js version: [e.g., 18.17.0]
        - Python version: [e.g., 3.10.12]
      value: |
        - OS: 
        - Browser: 
        - Node.js version: 
        - Python version: 
    validations:
      required: false
  
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any relevant error messages or logs
      placeholder: Paste error logs here...
      render: shell
    validations:
      required: false
  
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop images here...
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: Add any other context about the problem here...
    validations:
      required: false
